services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

  web-angular:
    build: ./client-web-angular
    ports:
      - "4200:4200"
      - "9229:9229"
    volumes:
      - ./client-web-angular:/app
      - /app/node_modules
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    command: ng serve --host 0.0.0.0 --poll 2000

  web-react:
    build:
      context: .
      dockerfile: client-web-react/Dockerfile
    ports:
      - "5173:5173"
      - "9231:9230"
    volumes:
      - ./client-web-react:/app
      - ./packages:/app/packages
      - /app/node_modules
      - /app/packages/testing/node_modules
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9230
      - DOCKER=true
      - VITE_API_URL=http://localhost:8000/api
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

volumes:
  postgres_data: